---
title: "Data_Analysis_project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#For my data analysis project, I am choosing to focus on opioid death rates in the State of Maryland and attempt to figure out why they are so high. We have been talking about opioid death rates as it relates to income in class and have found generally that the poorer states have the higher opioid death rates. However, Maryland is the richest state in the union by median household income. I would like to figure out what accounts for this dissonance.

```

```{r}

library(arcos)
library(tidyverse)
library(janitor)
library(tidycensus)
library(scales)

```

```{r}

key <- "uO4EK6I"

```

```{r}

#1 What county in Maryland had the most pills shipped per year?

maryland_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names() %>%
   select(buyer_state, buyer_county, year, dosage_unit, countyfips) %>%
  filter(buyer_state == "MD")

```

```{r}

#2 What Maryland county was most populous from 2006-2012?

maryland_county_population_per_year <- county_population(key = key) %>%
  clean_names() %>%
   select(buyer_state, buyer_county, year, population, countyfips) %>%
  filter(buyer_state == "MD")

```

```{r}
#3 What county in Maryland had the most pills person from 2006-2012?

pills_population <- maryland_county_pills_per_year %>%
  inner_join(maryland_county_population_per_year, by="countyfips")

```

```{r}

maryland_pills_population <- pills_population %>%
  select(countyfips, buyer_county.x, buyer_state.x, population, dosage_unit) %>%
  rename(buyer_county = buyer_county.x, buyer_state = buyer_state.x)


```

```{r}
#4 Loading the census data

census_api_key("549950d36c22ff16455fe196bbbd01d63cfbe6cf", install = TRUE, overwrite = TRUE)

```

```{r}

#5 Finding the county income data 

maryland_county_income <- get_acs(geography = "county",  variables = c(medincome = "B19013_001"), state = "MD", key=key)

```

```{r}

#6 Finding the state income data for all states 

all_state_incomes <- get_acs(geography = "state", variables = "B19013_001")

```

```{r}

#7 Finding the margin of errors in census data 

moe_sum(moe, estimate = NULL, na.rm = FALSE)

```

```{r}

#8 

maryland_county_income_subdivisions <- get_acs(geography = "county subdivision", variables = c(medincome = "B19013_001"), state = "MD", key=key)

```

```{r}
#9 What are the richest and poorest districts in Baltimore County?

#Dundalk in District 12 and Monkton/Phoenix in District 10 are the poorest and richest districts in Baltimore County based on median household income, according to the census data 

#10 What are the richest and poorest districts in Montgomery County?

#Gaithersburg/Germantown/Montgomery District and Potomac are the poorest and richets districts in Montogomery County based on median household income, according to the census data 

#11 What district in West Virginia, the poorest state, compares to a district in Maryland?

wv_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names() %>%
   select(buyer_state, buyer_county, year, dosage_unit, countyfips) %>%
  filter(buyer_state == "WV")

wv_county_population_per_year <- county_population(key = key) %>%
  clean_names() %>%
   select(buyer_state, buyer_county, year, population, countyfips) %>%
  filter(buyer_state == "WV")

pills_population_wv <- wv_county_pills_per_year %>%
  inner_join(wv_county_population_per_year, by="countyfips")

wv_pills_population <- pills_population_wv %>%
  select(countyfips, buyer_county.x, buyer_state.x, population, dosage_unit) %>%
  rename(buyer_county = buyer_county.x, buyer_state = buyer_state.x)

```

```{r}

#12 What pharmacies received the most pills in Baltimore County?

baltimore_county_pharmacies <- total_pharmacies_county(county= "BALTIMORE", key = key)

```

```{r}

#13 What distributors shipped the most pills to Baltimore County? 

total_distributors_county(county= "BALTIMORE", key = key)

```

```{r}

#14 and 15 Are there certain distributors that focus their pill distribution in the poorer areas of Maryland?

#How does this relate to the rest of the country? I am unsure of how to answer these two questions currently, but I would like to answer them because I believe they may yield interesting answers. 

```

```{r}
#Next I want to explore more of the makeup of the poor areas affected by the opioid crisis 

#16 How many black people live in Baltimore County? 

baltimore_county_black <- get_acs(geography = "county", variables = c("B02001_003"), year = 2012)

#17 How many of those black people live in Dundalk (one of the poorer areas of the county I outlined)?

dundalk_black <- get_acs(geography = "county subdivision", variables = c("B02001_003"), year = 2012, state="MD")


#18 How many black people are in counties in West Virginia?

West_Virginia_black <- get_acs(geography = "county", variables = c("B02001_003"), year = 2012, state="MD")

#19 What is the racial makeup of states with a low number of pill shipments?

All_states_black <- get_acs(geography = "state", variables = c("B02001_003"), year = 2012)

```

```{r}

#I also want to look at how urban and rural areas compared in opioid usage in Maryland and in the country at large

#20 How many pills were distributed to the rural counties of Maryland?

maryland_rural_pills <- maryland_county_pills_per_year %>%
   select(buyer_state, buyer_county, year, dosage_unit, countyfips)%>%
  filter(buyer_county %in% c("ALLEGANY", "WASHINGTON", "FREDERICK", "CARROLL", "HARFORD", "CECIL", "KENT", "QUEEN ANNES", "CAROLINE", "TALBOT", "DORCHESTER", "WICOMICO", "WORCESTER", "SOMERSET", "CHARLES", "CALVERT", "SAINT MARYS"))%>%
  mutate(dosage_unit, total_pills = sum(dosage_unit)) 
  

#21 How many pills were distributed to majority urban/suburban counties in Maryland?

maryland_urban_pills <- maryland_county_pills_per_year %>%
  clean_names() %>%
   select(buyer_state, buyer_county, year, dosage_unit, countyfips) %>%
  filter(buyer_county %in% c("BALTIMORE", "BALTIMORE CITY", "MONTGOMERY", "HOWARD", "ANNE ARUNDEL", "PRINCE GEORGES"))%>%
  mutate(dosage_unit, total_pills =sum(dosage_unit))

```

```{r}
maryland_urban_pills_population <- maryland_urban_pills %>%
  inner_join(maryland_county_population_per_year, by="countyfips")%>%
  select(buyer_state.x, buyer_county.x, dosage_unit, total_pills, year.y, population) %>%
  mutate(population, total_population =sum(population))%>%
  mutate(total_pills, pills_per_person =(total_pills/total_population))

#Urban counties in Maryland acccount for 86 percent of Maryland's black population

```

```{r}

maryland_rural_pills_population <- maryland_rural_pills %>%
  inner_join(maryland_county_population_per_year, by="countyfips")%>%
  select(buyer_state.x, buyer_county.x, dosage_unit, total_pills, year.y, population) %>%
  mutate(population, total_population =sum(population))%>%
  mutate(total_pills, pills_per_person =(total_pills/total_population))

```

```{r}

#22 What percentage of Maryland's population live in the urban/suburban areas?

#23 What percentage of Maryland's population live in the rural areas?

#This can be taken from the county population data set 

```

```{r}

#24 How many pills were distributed to urban counties in West Virginia?

wv_urban_pills <- wv_county_pills_per_year %>%
  clean_names() %>%
   select(buyer_state, buyer_county, year, dosage_unit, countyfips) %>%
  filter(buyer_county %in% c("BERKELEY", "BROOKE", "CABELL", "HANCOCK", "JEFFERSON", "KANAWHA", "MARSHALL", "MINERAL", "OHIO", "PUTNAM", "WAYNE", "WOOD"))%>%
  mutate(dosage_unit, total_pills =sum(dosage_unit))

#25 How many pills were distributed to rural counties in West Virginia?

wv_rural_pills <- wv_county_pills_per_year %>%
  clean_names() %>%
   select(buyer_state, buyer_county, year, dosage_unit, countyfips) %>%
  filter(buyer_county %in% c("BARBOUR", "BOONE", "BRAXTON", "CALHOUN", "CLAY", "DODDRIDGE", "FAYETTE", "GILMER", "GRANT", "GREENBRIER", "HAMPSHIRE", "HARDY", "HARRISON", "JACKSON", "LEWIS", "LINCOLN", "LOGAN", "MARION", "MASON", "MCDOWELL", "MERCER", "MINGO", "MONONGALIA", "MONROE", "MORGAN", "NICHOLAS", "PENDLETON", "PLEASANTS", "POCAHONTAS", "PRESTON", "RALEIGH", "RANDOLPH", "RITCHIE", "ROANE", "SUMMERS", "TAYLOR", "TUCKER", "TYLER", "UPSHUR", "WEBSTER", "WETZEL", "WIRT", "WYOMING"))%>%
  mutate(dosage_unit, total_pills =sum(dosage_unit))

#26 What percentage of West Virginia's population live in the urban/suburban areas?

#27 What percentage of West Virginia's population live in the rural areas?

#This can be taken from the county population data set 

```

```{r}

wv_urban_pills_population <- wv_urban_pills %>%
  inner_join(wv_county_population_per_year, by="countyfips")%>%
  select(buyer_state.x, buyer_county.x, dosage_unit, total_pills, year.y, population) %>%
  mutate(population, total_population =sum(population))%>%
  mutate(total_pills, pills_per_person =(total_pills/total_population))

#WV's urban population accounts for 49.6 percent of the black population in the state. 

```

```{r}
wv_rural_pills_population <- wv_rural_pills %>%
  inner_join(wv_county_population_per_year, by="countyfips")%>%
  select(buyer_state.x, buyer_county.x, dosage_unit, total_pills, year.y, population) %>%
  mutate(population, total_population =sum(population))%>%
  mutate(total_pills, pills_per_person =(total_pills/total_population))

```